task/workflow
qiniu-ava/handbook pull request #41
Opened 2018-12-18 13:33 UTC by houz42

2018-12-19 03:03 UTC, zjy-yuzai reviewed
lgtm

2018-12-19 03:06 UTC, zjy-yuzai commented on 05-tasks/5.6-workflow.md
> +下图工作流模版配置页面中, 左侧为可选择的任务定义列表和已定义的其它工作流模版列表, 点击任务定义或模版名称右侧的加号, 可将选择的任务定义或者工作流模版作为新工作流模版的一个结点添加到中部工作流配置面板:
句子有点长，建议去掉【新工作流模版的】

2018-12-19 03:08 UTC, zjy-yuzai commented on 05-tasks/5.6-workflow.md
> +任务或子模版声明的输入参数需要绑定来源, 可以绑定至其它结点的输出, 或工作流全局输入.
【可以绑定至其它结点的输出】，这个分句有点疑惑，加点具体解释

2018-12-19 03:12 UTC, zjy-yuzai commented on 05-tasks/5.6-workflow.md
> +一个结点直接或间接依赖的结点的输出参数值可以用作该结点的输入参数值. 以上图连接为例, 如要将 `task-demo` 结点的输出参数 `result` 作为 `echo` 结点输入参数 `word` 的值, 则选中 `word` 结点, 在右侧输入绑定面板即可列出 `word` 结点的输入参数列表, 点击 `word` 参数右侧下拉框可以看到可选的其它结点的输出参数列表:
【一个结点直接或间接依赖的结点的输出参数值可以用作该结点的输入参数值】，谁依赖谁，还是被依赖，有点迷糊，要不用A、B结点来表示

2018-12-19 03:14 UTC, zjy-yuzai commented on 05-tasks/5.6-workflow.md
> +输入参数绑定结束, 点击面板右侧下一步, 可以绑定输出参数. 绑定输出参数即为将一些结点的输出参数声明为工作流模版的全局输出.
【绑定输出参数即为：将一些结点的输出参数，声明为工作流模版的全局输出】，是不是这样断个句比较好

2018-12-19 03:15 UTC, zjy-yuzai commented on 05-tasks/5.6-workflow.md
> +之后右侧变为输出参数绑定面板, 列出了刚才声明的全局输出列表, 可以用类似绑定输入参数的方式选择某个结点的某个输出绑定至该全局输出:
【可以用类似绑定输入参数的方式，选择某个结点的某个输出，绑定至该全局输出】

2018-12-19 03:30 UTC, gaobonan commented on 05-tasks/5.6-workflow.md
> +任务定义的执行入口与训练类似. 这里可以引用输入参数, 形如 `{{inputs.parameters.param}}`. 运行时, 双花括号中的内容会被替换为参数 `param` 的取值. 如下图中任务定义, 若执行时传入 `param` 的值为 `bye world`, 则运行时的执行入口为 `echo "bye world" && ...`.
双花括号-》双括号

2018-12-19 03:30 UTC, gaobonan commented on 05-tasks/5.6-workflow.md
> +下图工作流模版配置页面中, 左侧为可选择的任务定义列表和已定义的其它工作流模版列表, 点击任务定义或模版名称右侧的加号, 可将选择的任务定义或者工作流模版作为新工作流模版的一个结点添加到中部工作流配置面板:
添加到中部工作流配置面板-》添加到工作流配置面板

2018-12-19 03:30 UTC, gaobonan commented on 05-tasks/5.6-workflow.md
> +任务或子模版声明的输入参数需要绑定来源, 可以绑定至其它结点的输出, 或工作流全局输入.
任务或子模版声明的输入参数需要绑定来源，可以绑定其(父节点的)*父节点的输出参数，或工作流全局输入

2018-12-19 03:54 UTC, gaobonan commented on 05-tasks/5.6-workflow.md
> +一个结点直接或间接依赖的结点的输出参数值可以用作该结点的输入参数值. 以上图连接为例, 如要将 `task-demo` 结点的输出参数 `result` 作为 `echo` 结点输入参数 `word` 的值, 则选中 `word` 结点, 在右侧输入绑定面板即可列出 `word` 结点的输入参数列表, 点击 `word` 参数右侧下拉框可以看到可选的其它结点的输出参数列表:
会不会改成“(父节点的)*父节点的输出参数”更加好理解一些，如果觉得解释的不清楚，也可以拿图中“tmpl-echo2"举例子，它可以绑定父节点(echo2,tmpl-echo2-3)的输出参数和父节点的父节点（task-demo）的输出参数。当然前提是他们有输出。

2018-12-19 03:54 UTC, gaobonan commented on 05-tasks/5.6-workflow.md
> +为每个全局输入参数指定一个值, 默认超时时间为一天, 也可以按需修改:
超时时间上限为七天

2018-12-19 07:45 UTC, Tanviw requested changes

2018-12-19 07:45 UTC, Tanviw commented on 05-tasks/5.6-workflow.md
> +任务定义可以选用同工作台和训练相同的公开镜像, 也可以使用自定义镜像或直接输入镜像地址:
可以选用同工作台和训练相同=>可以选用与工作台和训练相同

2018-12-19 07:45 UTC, Tanviw commented on 05-tasks/5.6-workflow.md
> +这里声明的输入参数, 可在任务执行入口或任务脚本中使用, 默认值可以留空, 可以声明多个输入参数, 如下图所示.
图呢？还是和下面的输出参数共用一张图？

2018-12-19 07:45 UTC, Tanviw commented on 05-tasks/5.6-workflow.md
> +下图工作流模版配置页面中, 左侧为可选择的任务定义列表和已定义的其它工作流模版列表, 点击任务定义或模版名称右侧的加号, 可将其添加到中间工作流配置面板, 作为新工作流模版的一个结点:
不用点击加号也可以，改为【点击任务定义或模版名称】吧。另外页面上显示的都是“节点”而非“结点”，我看到其他地方的工作流或者图也是用的“节点”这个名词。

2018-12-19 07:45 UTC, Tanviw commented on 05-tasks/5.6-workflow.md
> +如果结点 B 直接或间接地依赖结点 A, 则可将结点 A 的任一输出参数值用作结点 B 的任一输入参数值. 以上图连接为例, 如要将 `task-demo` 结点的输出参数 `result` 作为 `echo` 结点输入参数 `word` 的值, 则选中 `word` 结点, 在右侧输入绑定面板即可列出 `word` 结点的输入参数列表, 点击 `word` 参数右侧下拉框可以看到可选的其它结点
作为 echo 节点的输入参数 word，后面一句话的两个 word 节点应该改成 echo 节点。

2018-12-19 07:45 UTC, Tanviw commented on 05-tasks/5.6-workflow.md
> +之后选中结点 `tmpl-echo2-3`, 即可在右侧输入绑定面板的下拉框中看到刚声明的全局参数 `global-param`:
看到刚声明的全局参数 =>看到上述声明的全局参数，这样更书面语一点

2018-12-19 07:45 UTC, Tanviw commented on 05-tasks/5.6-workflow.md
> +输入参数绑定结束, 点击面板右侧下一步, 可以绑定输出参数. 即: 将结点的一些输出参数声明为工作流模版的全局输出.
这一步之前最好加个注释说明一下，图中节点如果有输入参数并且输入参数没有默认值的情况下，必须绑定输入参数，才能进入下一步。另外标注一下 输出参数是可选的

2018-12-19 07:45 UTC, Tanviw commented on 05-tasks/5.6-workflow.md
> +之后右侧变为输出参数绑定面板, 列出了刚才声明的全局输出列表, 可以用类似绑定输入参数的方式，选择某个结点的某个输出，绑定至该全局输出:
刚才=>上述

2018-12-19 07:45 UTC, Tanviw commented on 05-tasks/5.6-workflow.md
> +到这里, 一个工作流模版就创建完成了, 可以在工作流模版列表页看到刚才创建的模版:
刚才

2018-12-19 07:45 UTC, Tanviw commented on SUMMARY.md
> -* [Introduction](readme.md)
Introduction为何删除

2018-12-19 07:46 UTC, houz42 commented on 05-tasks/5.6-workflow.md
> +这里声明的输入参数, 可在任务执行入口或任务脚本中使用, 默认值可以留空, 可以声明多个输入参数, 如下图所示.
一起的

2018-12-19 07:47 UTC, houz42 commented on 05-tasks/5.6-workflow.md
> +下图工作流模版配置页面中, 左侧为可选择的任务定义列表和已定义的其它工作流模版列表, 点击任务定义或模版名称右侧的加号, 可将其添加到中间工作流配置面板, 作为新工作流模版的一个结点:
这两个词还是有差异的, 这个地方应该用 "结点"

2018-12-19 07:48 UTC, Tanviw commented on 05-tasks/5.6-workflow.md
> +下图工作流模版配置页面中, 左侧为可选择的任务定义列表和已定义的其它工作流模版列表, 点击任务定义或模版名称右侧的加号, 可将其添加到中间工作流配置面板, 作为新工作流模版的一个结点:
应该用“节点”。

2018-12-19 07:59 UTC, houz42 commented on SUMMARY.md
> -* [Introduction](readme.md)
不影响目录结构 Introduction 是自动生成的

2018-12-20 02:04 UTC, Tanviw approved these changes

2018-12-20 06:36 UTC, merged